#pragma once
#include <raylib.h>
#include <stdbool.h>

#define DEFAULT_SCREENWIDTH 1000
#define DEFAULT_SCREENHEIGHT 600
#define MINSIZE_WIDTH 300
#define MINSIZE_HEIGHT 300
#define WINDOW_TITLE "raylib image editor"
#define AA_FRAMEBUFFER true
#define SMOOTH_SCALE_BY_DEFAULT true
#define ENABLE_FPS_COUNTER false

#define DEFAULT_BOX_COLOR SKYBLUE
#define DEFAULT_CROP_COLOR DARKGREEN
#define DEFAULT_LINE_COLOR RED
#define DEFAULT_TEXT_COLOR DARKGREEN
#define DEFAULT_CURSOR_COLOR RED
